import assert from 'node:assert/strict';
import test from 'node:test';
import { ALL_PROJECTS_BRIEFING_SCOPE } from '../../../src/domain/briefing/BriefingScope';
import { DailyRollupGenerator, type DailyRollupWriter } from '../../../src/application/rollup/DailyRollupGenerator';
import type { RenderedDailyRollup } from '../../../src/application/rollup/RollupMarkdownRenderer';
import type { Project } from '../../../src/domain/project/Project';
import type { RollupFinding } from '../../../src/domain/rollup/RollupFinding';
import type { DailyRollupSettings, ImportedSbomConfig } from '../../../src/application/use-cases/types';
import type { SelectRollupFindings } from '../../../src/application/rollup/SelectRollupFindings';
import type { RollupMarkdownRenderer } from '../../../src/application/rollup/RollupMarkdownRenderer';
import { DailyRollupNoteWriter, type DailyRollupVaultAdapter } from '../../../src/infrastructure/obsidian/DailyRollupNoteWriter';
import type { ComponentRelationshipGraph } from '../../../src/application/sbom/types';
import type { RollupFindingProjection } from '../../../src/application/rollup/RollupFindingProjector';

const settings: DailyRollupSettings = {
  autoGenerateOnFirstSyncOfDay: false,
  excludedTriageStates: ['mitigated', 'false_positive', 'suppressed'],
  folderPath: 'VulnDash Briefings',
  includeUnmappedFindings: true,
  lastAutoGeneratedOn: '',
  severityThreshold: 'HIGH'
};

const projects: Project[] = [
  {
    createdAt: '2026-04-18T00:00:00.000Z',
    id: 'project::portal-web',
    name: 'Portal Web',
    updatedAt: '2026-04-18T00:00:00.000Z'
  },
  {
    createdAt: '2026-04-18T00:00:00.000Z',
    id: 'project::identity-api',
    name: 'Identity API',
    updatedAt: '2026-04-18T00:00:00.000Z'
  }
];

const sboms: ImportedSbomConfig[] = [
  {
    contentHash: 'hash-portal',
    enabled: true,
    id: 'sbom-portal',
    label: 'portal-web.cdx.json',
    lastImportedAt: 0,
    path: 'reports/portal-web.cdx.json',
    projectId: 'project::portal-web',
    projectNameSnapshot: 'Portal Web'
  },
  {
    contentHash: 'hash-identity',
    enabled: true,
    id: 'sbom-identity',
    label: 'identity-api.spdx.json',
    lastImportedAt: 0,
    path: 'reports/identity-api.spdx.json',
    projectId: 'project::identity-api',
    projectNameSnapshot: 'Identity API'
  }
];

const createFinding = (overrides: Partial<RollupFinding> = {}): RollupFinding => ({
  affectedProjects: [{
    displayName: 'Portal Web',
    notePath: 'Projects/Portal.md',
    sourceSbomIds: ['sbom-portal'],
    sourceSbomLabels: ['portal-web.cdx.json'],
    status: 'linked'
  }],
  key: 'NVD:CVE-2026-4000',
  triageRecord: null,
  triageState: 'active',
  unmappedSboms: [],
  vulnerability: {
    affectedProducts: [],
    cvssScore: 8.6,
    hydrationState: 'complete',
    id: 'CVE-2026-4000',
    publishedAt: '2026-04-18T00:00:00.000Z',
    references: [],
    severity: 'HIGH',
    source: 'NVD',
    summary: 'Summary',
    title: 'Title',
    updatedAt: '2026-04-18T00:00:00.000Z'
  },
  ...overrides
});

const emptyRelationshipGraph: ComponentRelationshipGraph = {
  allSeveritiesByComponent: new Map(),
  componentsByVulnerability: new Map(),
  relationships: [],
  vulnerabilitiesByComponent: new Map(),
  vulnerabilitiesByOccurrence: new Map()
};

test('DailyRollupGenerator orchestrates selection, rendering, and writing', async () => {
  const findings: RollupFinding[] = [];
  const calls: string[] = [];
  const selector = {
    execute: (input: { readonly date?: string; }) => {
      calls.push('select');
      assert.equal(input.date, undefined);
      return findings;
    }
  } as unknown as SelectRollupFindings;
  const rendered: RenderedDailyRollup = {
    analystNotesHeading: '## Analyst Notes',
    analystNotesPlaceholder: '- Placeholder',
    fileName: 'VulnDash Briefing 2026-04-18.md',
    managedSections: [],
    title: '# VulnDash Briefing 2026-04-18'
  };
  const renderer = {
    render: (input: { readonly date: string; readonly findings: readonly RollupFindingProjection[]; readonly scope: { readonly displayLabel: string; }; }) => {
      calls.push('render-fallback');
      assert.equal(input.date, '2026-04-18');
      assert.equal(input.findings.length, findings.length);
      assert.equal(input.scope.displayLabel, 'All Projects');
      return rendered;
    }
  } as unknown as RollupMarkdownRenderer;
  const writer: DailyRollupWriter = {
    write: async (input) => {
      calls.push('write');
      assert.equal(input.date, '2026-04-18');
      assert.equal(input.document, rendered);
      assert.equal(input.folderPath, 'VulnDash Briefings');
      return {
        content: '# VulnDash Briefing 2026-04-18',
        created: true,
        path: 'VulnDash Briefings/VulnDash Briefing 2026-04-18.md'
      };
    }
  };
  const asyncTaskCoordinator = {
    execute: async (_taskKind: 'render-daily-rollup', payload: { readonly date: string; readonly findings: readonly RollupFindingProjection[]; }) => {
      calls.push('render');
      assert.equal(payload.date, '2026-04-18');
      assert.equal(payload.findings.length, findings.length);
      return {
        document: rendered
      };
    }
  };

  const result = await new DailyRollupGenerator(selector, renderer, writer, asyncTaskCoordinator as never).execute({
    affectedProjectsByVulnerabilityRef: new Map(),
    date: '2026-04-18',
    projects: [],
    relationshipGraph: emptyRelationshipGraph,
    scope: ALL_PROJECTS_BRIEFING_SCOPE,
    settings,
    sboms: [],
    triageByCacheKey: new Map(),
    vulnerabilities: []
  });

  assert.deepEqual(calls, ['select', 'render', 'write']);
  assert.equal(result.findingsCount, 0);
  assert.equal(result.path, 'VulnDash Briefings/VulnDash Briefing 2026-04-18.md');
});

class InMemoryRollupVault implements DailyRollupVaultAdapter {
  public readonly createdFiles: string[] = [];
  public readonly createdFolders: string[] = [];
  public readonly writes: string[] = [];

  public constructor(
    private readonly entries = new Map<string, string>()
  ) {}

  public async create(path: string, content: string): Promise<void> {
    this.createdFiles.push(path);
    this.entries.set(path, content);
  }

  public async createFolder(path: string): Promise<void> {
    this.createdFolders.push(path);
    this.entries.set(path, '__folder__');
  }

  public async exists(path: string): Promise<boolean> {
    return this.entries.has(path);
  }

  public async read(path: string): Promise<string> {
    const content = this.entries.get(path);
    if (content === undefined) {
      throw new Error('ENOENT');
    }

    return content;
  }

  public async write(path: string, content: string): Promise<void> {
    this.writes.push(path);
    this.entries.set(path, content);
  }

  public get(path: string): string | undefined {
    return this.entries.get(path);
  }
}

const createRenderedDocument = (): RenderedDailyRollup => ({
  analystNotesHeading: '## Analyst Notes',
  analystNotesPlaceholder: '- Add analyst notes, escalation context, and follow-up decisions here.',
  fileName: 'VulnDash Briefing 2026-04-18.md',
  managedSections: [{
    content: '## Findings Overview\n\n- Critical issue',
    key: 'daily-rollup'
  }],
  title: '# VulnDash Briefing 2026-04-18'
});

test('DailyRollupNoteWriter creates a new rollup note when one does not exist', async () => {
  const vault = new InMemoryRollupVault();
  const writer = new DailyRollupNoteWriter(vault);

  const result = await writer.write({
    date: '2026-04-18',
    document: createRenderedDocument(),
    folderPath: 'briefings/daily'
  });

  assert.equal(result.created, true);
  assert.equal(result.path, 'briefings/daily/VulnDash Briefing 2026-04-18.md');
  assert.deepEqual(vault.createdFolders, ['briefings', 'briefings/daily']);
  assert.deepEqual(vault.createdFiles, ['briefings/daily/VulnDash Briefing 2026-04-18.md']);
  assert.equal(vault.get(result.path), result.content);
});

test('DailyRollupNoteWriter updates an existing rollup note while preserving analyst notes', async () => {
  const notePath = 'briefings/daily/VulnDash Briefing 2026-04-18.md';
  const vault = new InMemoryRollupVault(new Map<string, string>([
    ['briefings', '__folder__'],
    ['briefings/daily', '__folder__'],
    [notePath, [
      '# VulnDash Briefing 2026-04-18',
      '',
      '## Analyst Notes',
      '',
      '- Existing analyst note',
      '',
      '<!-- VULNDASH:SECTION daily-rollup START -->',
      'Old content',
      '<!-- VULNDASH:SECTION daily-rollup END -->'
    ].join('\n')]
  ]));
  const writer = new DailyRollupNoteWriter(vault);

  const result = await writer.write({
    date: '2026-04-18',
    document: createRenderedDocument(),
    folderPath: 'briefings/daily'
  });

  assert.equal(result.created, false);
  assert.deepEqual(vault.createdFiles, []);
  assert.deepEqual(vault.writes, [notePath]);
  assert.match(result.content, /Existing analyst note/);
  assert.match(result.content, /Critical issue/);
});

test('DailyRollupGenerator filters findings for a single-project briefing before rendering', async () => {
  const findings: RollupFinding[] = [
    createFinding(),
    createFinding({
      affectedProjects: [{
        displayName: 'Identity API',
        notePath: 'Projects/Identity.md',
        sourceSbomIds: ['sbom-identity'],
        sourceSbomLabels: ['identity-api.spdx.json'],
        status: 'linked'
      }],
      key: 'NVD:CVE-2026-4001',
      vulnerability: {
        affectedProducts: [],
        cvssScore: 9.1,
        hydrationState: 'complete',
        id: 'CVE-2026-4001',
        publishedAt: '2026-04-18T00:00:00.000Z',
        references: [],
        severity: 'CRITICAL',
        source: 'NVD',
        summary: 'Summary',
        title: 'Identity finding',
        updatedAt: '2026-04-18T00:00:00.000Z'
      }
    })
  ];
  const selector = {
    execute: () => findings
  } as unknown as SelectRollupFindings;
  let renderedFindings: readonly RollupFindingProjection[] = [];
  let renderedMatchedComponentCount = 0;
  let renderedScopeLabel = '';
  const rendered: RenderedDailyRollup = {
    analystNotesHeading: '## Analyst Notes',
    analystNotesPlaceholder: '- Placeholder',
    fileName: 'VulnDash Briefing 2026-04-18 - Portal Web.md',
    managedSections: [],
    title: '# VulnDash Briefing 2026-04-18 - Portal Web'
  };
  const renderer = {
    render: (input: { readonly findings: readonly RollupFindingProjection[]; readonly scope: { readonly displayLabel: string; }; }) => {
      renderedFindings = input.findings;
      renderedMatchedComponentCount = input.findings[0]?.matchedComponents.length ?? 0;
      renderedScopeLabel = input.scope.displayLabel;
      return rendered;
    }
  } as unknown as RollupMarkdownRenderer;
  const writer: DailyRollupWriter = {
    write: async () => ({
      content: rendered.title,
      created: true,
      path: 'VulnDash Briefings/VulnDash Briefing 2026-04-18 - Portal Web.md'
    })
  };

  await new DailyRollupGenerator(selector, renderer, writer, {
    execute: async (_taskKind: 'render-daily-rollup', payload: { readonly findings: readonly RollupFindingProjection[]; readonly scope: { readonly displayLabel: string; }; }) => ({
      document: renderer.render(payload as never)
    })
  } as never).execute({
    affectedProjectsByVulnerabilityRef: new Map(),
    date: '2026-04-18',
    projects,
    relationshipGraph: emptyRelationshipGraph,
    scope: {
      projectId: 'project::portal-web',
      type: 'single-project'
    },
    settings,
    sboms,
    triageByCacheKey: new Map(),
    vulnerabilities: []
  });

  assert.equal(renderedScopeLabel, 'Portal Web');
  assert.deepEqual(renderedFindings.map((finding) => finding.vulnerability.id), ['CVE-2026-4000']);
  assert.equal(renderedMatchedComponentCount, 0);
});

test('DailyRollupGenerator filters findings for a multi-project briefing before rendering', async () => {
  const findings: RollupFinding[] = [
    createFinding(),
    createFinding({
      affectedProjects: [{
        displayName: 'Identity API',
        notePath: 'Projects/Identity.md',
        sourceSbomIds: ['sbom-identity'],
        sourceSbomLabels: ['identity-api.spdx.json'],
        status: 'linked'
      }],
      key: 'NVD:CVE-2026-4001',
      vulnerability: {
        affectedProducts: [],
        cvssScore: 9.1,
        hydrationState: 'complete',
        id: 'CVE-2026-4001',
        publishedAt: '2026-04-18T00:00:00.000Z',
        references: [],
        severity: 'CRITICAL',
        source: 'NVD',
        summary: 'Summary',
        title: 'Identity finding',
        updatedAt: '2026-04-18T00:00:00.000Z'
      }
    }),
    createFinding({
      affectedProjects: [],
      key: 'GHSA-legacy-4002',
      unmappedSboms: [{
        sbomId: 'sbom-legacy',
        sbomLabel: 'legacy.cdx.json'
      }],
      vulnerability: {
        affectedProducts: [],
        cvssScore: 7.5,
        hydrationState: 'complete',
        id: 'GHSA-legacy-4002',
        publishedAt: '2026-04-18T00:00:00.000Z',
        references: [],
        severity: 'HIGH',
        source: 'GitHub',
        summary: 'Summary',
        title: 'Legacy finding',
        updatedAt: '2026-04-18T00:00:00.000Z'
      }
    })
  ];
  const selector = {
    execute: () => findings
  } as unknown as SelectRollupFindings;
  let renderedFindings: readonly RollupFindingProjection[] = [];
  let renderedScopeLabel = '';
  const rendered: RenderedDailyRollup = {
    analystNotesHeading: '## Analyst Notes',
    analystNotesPlaceholder: '- Placeholder',
    fileName: 'VulnDash Briefing 2026-04-18 - 2 Projects (Identity API, Portal Web).md',
    managedSections: [],
    title: '# VulnDash Briefing 2026-04-18 - 2 Projects (Identity API, Portal Web)'
  };
  const renderer = {
    render: (input: { readonly findings: readonly RollupFindingProjection[]; readonly scope: { readonly displayLabel: string; }; }) => {
      renderedFindings = input.findings;
      renderedScopeLabel = input.scope.displayLabel;
      return rendered;
    }
  } as unknown as RollupMarkdownRenderer;
  const writer: DailyRollupWriter = {
    write: async () => ({
      content: rendered.title,
      created: true,
      path: 'VulnDash Briefings/VulnDash Briefing 2026-04-18 - 2 Projects (Identity API, Portal Web).md'
    })
  };

  await new DailyRollupGenerator(selector, renderer, writer, {
    execute: async (_taskKind: 'render-daily-rollup', payload: { readonly findings: readonly RollupFindingProjection[]; readonly scope: { readonly displayLabel: string; }; }) => ({
      document: renderer.render(payload as never)
    })
  } as never).execute({
    affectedProjectsByVulnerabilityRef: new Map(),
    date: '2026-04-18',
    projects,
    relationshipGraph: emptyRelationshipGraph,
    scope: {
      projectIds: ['project::identity-api', 'project::portal-web'],
      type: 'multiple-projects'
    },
    settings,
    sboms,
    triageByCacheKey: new Map(),
    vulnerabilities: []
  });

  assert.equal(renderedScopeLabel, '2 Projects (Identity API, Portal Web)');
  assert.deepEqual(
    renderedFindings.map((finding) => finding.vulnerability.id),
    ['CVE-2026-4000', 'CVE-2026-4001']
  );
});

test('DailyRollupNoteWriter uses the rendered file name for scoped briefings', async () => {
  const vault = new InMemoryRollupVault();
  const writer = new DailyRollupNoteWriter(vault);

  const result = await writer.write({
    date: '2026-04-18',
    document: {
      ...createRenderedDocument(),
      fileName: 'VulnDash Briefing 2026-04-18 - Portal Web.md',
      title: '# VulnDash Briefing 2026-04-18 - Portal Web'
    },
    folderPath: 'briefings/daily'
  });

  assert.equal(result.path, 'briefings/daily/VulnDash Briefing 2026-04-18 - Portal Web.md');
});
